# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YEAAH(object):
    def setupUi(self, YEAAH):
        YEAAH.setObjectName("YEAAH")
        YEAAH.resize(324, 379)
        font = QtGui.QFont()
        font.setPointSize(11)
        YEAAH.setFont(font)
        YEAAH.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255))")
        self.centralwidget = QtWidgets.QWidget(YEAAH)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_generate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generate.setGeometry(QtCore.QRect(90, 280, 131, 28))
        self.btn_generate.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255))")
        self.btn_generate.setObjectName("btn_generate")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(40, 0, 221, 31))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(15)
        self.title.setFont(font)
        self.title.setStyleSheet("border: 2 px solid dashed ")
        self.title.setObjectName("title")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 2 px solid dashed ")
        self.label_2.setObjectName("label_2")
        self.cb_leter = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_leter.setGeometry(QtCore.QRect(20, 130, 221, 20))
        self.cb_leter.setObjectName("cb_leter")
        self.cb_num = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_num.setGeometry(QtCore.QRect(20, 170, 241, 20))
        self.cb_num.setObjectName("cb_num")
        YEAAH.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(YEAAH)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 324, 26))
        self.menubar.setObjectName("menubar")
        YEAAH.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(YEAAH)
        self.statusbar.setObjectName("statusbar")
        YEAAH.setStatusBar(self.statusbar)

        self.retranslateUi(YEAAH)
        QtCore.QMetaObject.connectSlotsByName(YEAAH)

    def retranslateUi(self, YEAAH):
        _translate = QtCore.QCoreApplication.translate
        YEAAH.setWindowTitle(_translate("YEAAH", "MainWindow"))
        self.btn_generate.setText(_translate("YEAAH", "Згенерувати"))
        self.title.setText(_translate("YEAAH", "Генератор паролів"))
        self.label_2.setText(_translate("YEAAH", "Тут буде результат!!"))
        self.cb_leter.setText(_translate("YEAAH", "Використовувати числа"))
        self.cb_num.setText(_translate("YEAAH", "Використовувати алфавіт"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    YEAAH = QtWidgets.QMainWindow()
    ui = Ui_YEAAH()
    ui.setupUi(YEAAH)
    YEAAH.show()
    sys.exit(app.exec_())
